# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 914fb1640b1627277ed689c68c9ad54a1e07f35eb1ffb65070beecdfcd21a7f356b781cbdef3b68bcc87c7be0d20eb05bffc83d15a5d78fc00caf2607006ed66

test:
  secret_key_base: 29ccdab48fe44c595712aa523dfa31fe48e8934c2e876b4c168513ee74dd2dab9882a4fa56eaa89e480b6a43f705c7889e0f5955bb501b0a902579a7c80e2b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
